// <auto-generated />
using System;
using AtmInsight.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AtmInsight.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AtmInsight.Domain.Entities.Cajero", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Latitud")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("Longitud")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Modelo")
                        .HasColumnType("longtext");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Cajeros");
                });

            modelBuilder.Entity("AtmInsight.Domain.Entities.ConsumoRepuesto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<long>("IncidenciaId")
                        .HasColumnType("bigint");

                    b.Property<long>("RepuestoId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("IncidenciaId");

                    b.HasIndex("RepuestoId");

                    b.ToTable("ConsumosRepuestos");
                });

            modelBuilder.Entity("AtmInsight.Domain.Entities.EstadisticaDiaria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AtmId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("MontoPromedio")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("TotalTransacciones")
                        .HasColumnType("int");

                    b.Property<int>("TransaccionesConsultaSaldo")
                        .HasColumnType("int");

                    b.Property<int>("TransaccionesDeposito")
                        .HasColumnType("int");

                    b.Property<int>("TransaccionesRetiro")
                        .HasColumnType("int");

                    b.Property<int>("UsuariosUnicos")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AtmId");

                    b.ToTable("EstadisticaDiarias");
                });

            modelBuilder.Entity("AtmInsight.Domain.Entities.Incidencia", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AtmId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaApertura")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Prioridad")
                        .HasColumnType("int");

                    b.Property<long?>("TecnicoId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AtmId");

                    b.HasIndex("TecnicoId");

                    b.ToTable("Incidencias");
                });

            modelBuilder.Entity("AtmInsight.Domain.Entities.Repuesto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Referencia")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("StokActual")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Repuestos");
                });

            modelBuilder.Entity("AtmInsight.Domain.Entities.Transaccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AtmId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(65,30)");

                    b.Property<bool>("ProcesadaEtl")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Resultado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TarjetaHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AtmId");

                    b.ToTable("Transacciones");
                });

            modelBuilder.Entity("AtmInsight.Domain.Entities.Usuario", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("IdiomaPreferido")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("AtmInsight.Domain.Entities.ConsumoRepuesto", b =>
                {
                    b.HasOne("AtmInsight.Domain.Entities.Incidencia", "Incidencia")
                        .WithMany("ConsumosRepuestos")
                        .HasForeignKey("IncidenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AtmInsight.Domain.Entities.Repuesto", "Repuesto")
                        .WithMany()
                        .HasForeignKey("RepuestoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Incidencia");

                    b.Navigation("Repuesto");
                });

            modelBuilder.Entity("AtmInsight.Domain.Entities.EstadisticaDiaria", b =>
                {
                    b.HasOne("AtmInsight.Domain.Entities.Cajero", "Cajero")
                        .WithMany("EstadisticasDiarias")
                        .HasForeignKey("AtmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cajero");
                });

            modelBuilder.Entity("AtmInsight.Domain.Entities.Incidencia", b =>
                {
                    b.HasOne("AtmInsight.Domain.Entities.Cajero", "Cajero")
                        .WithMany("Incidencias")
                        .HasForeignKey("AtmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AtmInsight.Domain.Entities.Usuario", "Tecnico")
                        .WithMany("IncidenciasAsignadas")
                        .HasForeignKey("TecnicoId");

                    b.Navigation("Cajero");

                    b.Navigation("Tecnico");
                });

            modelBuilder.Entity("AtmInsight.Domain.Entities.Transaccion", b =>
                {
                    b.HasOne("AtmInsight.Domain.Entities.Cajero", "Cajero")
                        .WithMany("Transacciones")
                        .HasForeignKey("AtmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cajero");
                });

            modelBuilder.Entity("AtmInsight.Domain.Entities.Cajero", b =>
                {
                    b.Navigation("EstadisticasDiarias");

                    b.Navigation("Incidencias");

                    b.Navigation("Transacciones");
                });

            modelBuilder.Entity("AtmInsight.Domain.Entities.Incidencia", b =>
                {
                    b.Navigation("ConsumosRepuestos");
                });

            modelBuilder.Entity("AtmInsight.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("IncidenciasAsignadas");
                });
#pragma warning restore 612, 618
        }
    }
}
